version: '3'

services:
  app:
    build:
      args:
        user: sling-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sling-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - sling:/var/www
    networks:
      - sling

  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - sling

  nginx:
    image: nginx:1.20-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - sling:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - sling

volumes:
  db:
  sling:

networks:
  sling:
    driver: bridge
