name: sling.loc
type: laravel
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
    - sling.loc
database:
    type: mariadb
    version: "10.11"
host_db_port: "3301"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
disable_settings_management: true
