name: Psalm Static analysis

on:
  push:
    branches:
    - main
    - develop
    paths:
    - '**.php'
    - 'psalm.xml'
  pull_request:
    branches:
    - main
    - develop
    paths:
    - '**.php'
    - 'psalm.xml'

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Psalm
      uses: docker://vimeo/psalm-github-actions
